runtime: python39 

env_variables: 
  OPENAI_KEY: "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"
  SENDER_EMAIL: "dj.eho.no23@gmail.com"
  SENDER_PASSWORD: "usuqfngsdehdikxe"

  SUPABASE_URL: "https://msfpfmwdawonueqaevru.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZnBmbXdkYXdvbnVlcWFldnJ1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3NTk5MTE5MSwiZXhwIjoxOTkxNTY3MTkxfQ.ImwsqoISh3zCKcAW0FJeB13UCWOCVay5Fm1U5TNwhUU"

  GPT_KEY: "YES"
  APP_VERSION: "3.6"

